# Generated by Django 4.1.3 on 2022-11-24 09:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('mobile_nu', models.CharField(blank=True, help_text='Please enter your name...', max_length=11, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09xxxxxxxxx'. Up to 11 digits allowed.", regex='^09(1[0-9]|3[1-9])-?[0-9]{3}-?[0-9]{4}$')], verbose_name='شماره موبایل')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='نام کاربری')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='نام خانوادگی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='مدیر')),
                ('mobile_is_validate', models.BooleanField(default=False, verbose_name='تایید شماره موبایل')),
                ('is_organization_admin', models.BooleanField(default=False, verbose_name='مدیر سازمان')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='زمان تغییر')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'ordering': ('username',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام پروفایل')),
                ('download_speed', models.CharField(help_text='مگابیت بر ثانیه، مقدار صفر به معنی بدون محدودیت سرعت است', max_length=10, verbose_name='حداکثر سرعت دانلود')),
                ('upload_speed', models.CharField(help_text='مگابیت بر ثانیه، مقدار صفر به معنی بدون محدودیت سرعت است', max_length=10, verbose_name='حداکثر سرعت آپلود')),
                ('is_limit_speed', models.BooleanField(default=0, help_text='درصورت غیر فعال بودن محدودیت سرعت برای این کاربر اعمال نخواهد شد', verbose_name='محدودیت سرعت')),
                ('daily_download', models.BigIntegerField(default=0, help_text='مگابایت', verbose_name='جداکثر دانلود روزانه')),
                ('monthly_download', models.BigIntegerField(default=0, help_text='مگابایت', verbose_name='جداکثر دانلود ماهانه')),
                ('is_limit_download', models.BooleanField(default=0, help_text='با فعال بودن این گزینه محاسبه مقدار استفاده بر اساس تنظیمات دانلود روزانه و ماهانه انجام می شود و اولویت این از بسته اینترنتی بالاتر است.', verbose_name='محدودیت دانلود')),
                ('is_voucher', models.BooleanField(default=0, help_text='با فعال بودن این گزینه کاربر می بایست بسته اینترنتی خریداری نماید.', verbose_name='بسته اینترنتی')),
                ('remain', models.IntegerField(default=0, help_text='به مگابایت', verbose_name='باقیمانده حجم')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='زمان تغییر')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام بسته اینترنتی')),
                ('volume', models.BigIntegerField(default=0, help_text='به مگابایت', verbose_name='حجم')),
                ('duration_day', models.IntegerField(default=0, verbose_name='مدت زمان-روز')),
                ('price', models.IntegerField(default=0, verbose_name='مبلغ')),
                ('is_valid', models.BooleanField(default=1, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remain', models.IntegerField(default=0, help_text='به مگابایت', verbose_name='باقیمانده حجم')),
                ('is_valid', models.BooleanField(default=1, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='زمان تغییر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('voucher_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.vouchertype')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام سازمان')),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.organization', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
