# Generated by Django 4.1.3 on 2022-11-24 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_user',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile', verbose_name='پروفایل کاربری'),
        ),
    ]
