# Generated by Django 4.1.3 on 2022-11-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_created_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_user',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده'),
        ),
    ]
