# Generated by Django 4.1.3 on 2022-12-03 04:56

import accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_organization_profile_alter_user_mobile_nu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mobile_is_validate',
            new_name='is_mobile_verified',
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_nu',
            field=models.CharField(blank=True, help_text='Please enter your name...', max_length=12, null=True, validators=[accounts.validators.validate_mobile_number], verbose_name='شماره موبایل'),
        ),
        migrations.CreateModel(
            name='MobileNuChanged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_nu', models.CharField(blank=True, help_text='Please enter your name...', max_length=12, null=True, validators=[accounts.validators.validate_mobile_number], verbose_name='شماره موبایل')),
                ('is_Verified', models.BooleanField(default=0, verbose_name='تایید شده')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
