# Generated by Django 4.1.3 on 2022-12-06 16:16

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_mobileverification_mobile_nu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilenuchanged',
            name='mobile_nu',
            field=models.CharField(blank=True, help_text='Please enter your name...', max_length=12, null=True, validators=[accounts.validators.validate_mobile_number], verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='mobileverification',
            name='mobile_nu',
            field=models.CharField(max_length=12, validators=[accounts.validators.validate_mobile_number], verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_nu',
            field=models.CharField(blank=True, help_text='Please enter your name...', max_length=12, null=True, validators=[accounts.validators.validate_mobile_number], verbose_name='شماره موبایل'),
        ),
    ]
