# Generated by Django 4.1.3 on 2022-12-09 06:12

import accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_mobilenuchanged_mobile_nu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilenuchanged',
            options={'verbose_name': 'شماره موبایلهای تغییر یافته'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'سازمان ها'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربران'},
        ),
        migrations.AlterModelOptions(
            name='voucher',
            options={'verbose_name': 'بسته های اینترنتی اختصاص داده شده'},
        ),
        migrations.AlterModelOptions(
            name='vouchertype',
            options={'verbose_name': 'بسته های اینترنتی'},
        ),
        migrations.RemoveField(
            model_name='mobilenuchanged',
            name='mobile_nu',
        ),
        migrations.AddField(
            model_name='mobilenuchanged',
            name='mobile_nu_new',
            field=models.CharField(blank=True, help_text='Please enter your name...', max_length=12, null=True, validators=[accounts.validators.validate_mobile_number], verbose_name='شماره موبایل جدید'),
        ),
        migrations.AddField(
            model_name='mobilenuchanged',
            name='mobile_nu_old',
            field=models.CharField(blank=True, help_text='Please enter your name...', max_length=12, null=True, validators=[accounts.validators.validate_mobile_number], verbose_name='شماره موبایل قدیم'),
        ),
        migrations.AddField(
            model_name='vouchertype',
            name='download_speed',
            field=models.CharField(default=0, help_text='مگابیت بر ثانیه، مقدار صفر به معنی بدون محدودیت سرعت است', max_length=10, verbose_name='حداکثر سرعت دانلود'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vouchertype',
            name='upload_speed',
            field=models.CharField(default=0, help_text='مگابیت بر ثانیه، مقدار صفر به معنی بدون محدودیت سرعت است', max_length=10, verbose_name='حداکثر سرعت آپلود'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voucher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.CreateModel(
            name='VoucherAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.voucher', verbose_name='بسته')),
            ],
            options={
                'verbose_name': 'کاربرانی که بسته اختصاص داده اند',
            },
        ),
    ]
