# Generated by Django 4.1.3 on 2022-12-10 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_mobilenuchanged_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoucherAssign',
        ),
    ]
