# Generated by Django 4.1.3 on 2022-12-11 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_delete_voucherassign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ('-is_valid', '-id'), 'verbose_name': 'بسته های اینترنتی کاربر', 'verbose_name_plural': 'بسته های اینترنتی کاربران'},
        ),
        migrations.AlterModelOptions(
            name='vouchertype',
            options={'ordering': ('-is_valid', '-id'), 'verbose_name': 'بسته اینترنتی', 'verbose_name_plural': 'بسته های اینترنتی'},
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='remain',
        ),
        migrations.AddField(
            model_name='voucher',
            name='used',
            field=models.IntegerField(default=0, help_text='به مگابایت', verbose_name='حجم مصرف شده'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.vouchertype', verbose_name='بسته حجمی'),
        ),
    ]
