# Generated by Django 4.1.3 on 2022-12-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_vouchertype_download_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchertype',
            name='download_speed',
            field=models.IntegerField(help_text='مگابیت بر ثانیه، مقدار صفر به معنی بدون محدودیت سرعت است', verbose_name='حداکثر سرعت دانلود'),
        ),
        migrations.AlterField(
            model_name='vouchertype',
            name='upload_speed',
            field=models.IntegerField(help_text='مگابیت بر ثانیه، مقدار صفر به معنی بدون محدودیت سرعت است', verbose_name='حداکثر سرعت آپلود'),
        ),
    ]
