# Generated by Django 4.1.3 on 2022-12-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_vouchertype_download_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='used',
            field=models.BigIntegerField(default=0, help_text='به مگابایت', verbose_name='حجم مصرف شده'),
        ),
    ]
