# Generated by Django 4.1.3 on 2022-12-20 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_voucher_pre_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_user',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده'),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=255, verbose_name='نام صفحه')),
                ('event', models.CharField(max_length=255, verbose_name='رویداد')),
                ('data', models.CharField(max_length=255, verbose_name='داده')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
