# Generated by Django 4.1.3 on 2022-12-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_created_user_useractivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'verbose_name': 'فعالیت کاربر', 'verbose_name_plural': 'فعالیت کاربران'},
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='data',
            field=models.TextField(verbose_name='داده'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='event',
            field=models.CharField(max_length=100, verbose_name='رویداد'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='form',
            field=models.CharField(max_length=30, verbose_name='نام صفحه'),
        ),
    ]
