# Generated by Django 4.1.3 on 2022-12-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_useractivity_options_alter_useractivity_data_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mobileverification',
            index=models.Index(fields=['user'], name='accounts_mo_user_id_807e01_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileverification',
            index=models.Index(fields=['user', 'expire_at'], name='accounts_mo_user_id_5260b9_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileverification',
            index=models.Index(fields=['user', 'revoked', 'expire_at'], name='accounts_mo_user_id_976a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileverification',
            index=models.Index(fields=['user', 'revoked', 'expire_at', 'code'], name='accounts_mo_user_id_d566ac_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileverification',
            index=models.Index(fields=['user', 'expire_at', 'code'], name='accounts_mo_user_id_9d1c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user'], name='accounts_us_user_id_ccfedd_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['created_date'], name='accounts_us_created_9a2572_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'created_date'], name='accounts_us_user_id_c1bd3e_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['user'], name='accounts_vo_user_id_753dca_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['assign_by'], name='accounts_vo_assign__7491af_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['is_valid'], name='accounts_vo_is_vali_98ea4f_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['created_date'], name='accounts_vo_created_819c59_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['user', 'is_valid', 'created_date'], name='accounts_vo_user_id_a12dc6_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['user', 'created_date'], name='accounts_vo_user_id_13dbba_idx'),
        ),
    ]
