# Generated by Django 4.1.3 on 2023-05-16 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_mobileverification_accounts_mo_user_id_807e01_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, help_text='به ریال', verbose_name='مبلغ')),
                ('success', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=255, verbose_name='توکن پرداخت')),
                ('message', models.CharField(max_length=255, verbose_name='پیام')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='زمان تغییر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('voucher_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_vouchettype', to='accounts.vouchertype', verbose_name='بسته حجمی')),
            ],
        ),
    ]
