# Generated by Django 4.1.3 on 2023-05-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(default=0, max_length=255, verbose_name='شماره پیگیری'),
            preserve_default=False,
        ),
    ]
