# Generated by Django 4.1.6 on 2023-05-19 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_payment_message_alter_payment_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_vouchet', to='accounts.voucher', verbose_name='بسته حجمی'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='voucher_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_vouchettype', to='accounts.vouchertype', verbose_name='نوع بسته حجمی'),
        ),
    ]
