# Generated by Django 4.1.6 on 2023-05-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_payment_voucher_alter_payment_voucher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='activate',
            field=models.BooleanField(default=True),
        ),
    ]
