# Generated by Django 4.1.3 on 2023-06-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_payment_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vouchertype',
            options={'ordering': ('duration_day', 'price'), 'verbose_name': 'بسته اینترنتی', 'verbose_name_plural': 'بسته های اینترنتی'},
        ),
    ]
