# Generated by Django 4.1.6 on 2023-06-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_vouchertype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع'),
        ),
    ]
