# Generated by Django 4.1.6 on 2023-12-23 12:55

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0034_voucher_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True, verbose_name="نام"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True, verbose_name="نام خانوادگی"
            ),
        ),
    ]
