# Generated by Django 4.1.6 on 2023-12-23 13:05

import accounts.validators
from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0035_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=encrypted_model_fields.fields.EncryptedCharField(
                verbose_name="نام سازمان"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile_nu",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True,
                help_text="Please enter your name...",
                null=True,
                validators=[accounts.validators.validate_mobile_number],
                verbose_name="شماره موبایل",
            ),
        ),
    ]
