# Generated by Django 4.1.6 on 2023-12-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0036_alter_organization_name_alter_user_mobile_nu"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="force_change_pass",
            field=models.BooleanField(default=False, verbose_name="تغییر کلمه عبور"),
        ),
    ]
