# Generated by Django 4.1.3 on 2022-11-24 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TerminateCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip_address', models.GenericIPAddressField(protocol='IPv4', verbose_name='آدرس شبکه کاربر')),
                ('dns_log', models.CharField(max_length=255, null=True, verbose_name='آدرس')),
                ('log_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Authenticate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nas_ip_address', models.GenericIPAddressField(protocol='IPv4', verbose_name='آدرس شبکه دستگاه')),
                ('nas_identifier', models.CharField(max_length=30, verbose_name='نام دستگاه')),
                ('user_ip_address', models.GenericIPAddressField(protocol='IPv4', verbose_name='آدرس شبکه کاربر')),
                ('acct_session_id', models.CharField(max_length=10, verbose_name='شناسه جلسه')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ورود')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nas_ip_address', models.GenericIPAddressField(protocol='IPv4', verbose_name='آدرس شبکه دستگاه')),
                ('nas_identifier', models.CharField(max_length=30, verbose_name='نام دستگاه')),
                ('user_ip_address', models.GenericIPAddressField(protocol='IPv4', verbose_name='آدرس شبکه کاربر')),
                ('acct_session_id', models.CharField(max_length=10, verbose_name='شناسه جلسه')),
                ('acct_input_octets', models.BigIntegerField(default=0, verbose_name='حجم آپلود')),
                ('acct_output_octets', models.BigIntegerField(default=0, verbose_name='حجم دانلود')),
                ('acct_input_packets', models.BigIntegerField(default=0, verbose_name='تعداد پکت ارسالی')),
                ('acct_output_packets', models.BigIntegerField(default=0, verbose_name='تعداد پکت دریافتی')),
                ('acct_session_time', models.IntegerField(default=0, verbose_name='زمان جلسه')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ورود')),
                ('logout_time', models.DateTimeField(null=True, verbose_name='زمان خروج')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین تغییر')),
                ('acct_status_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiuslog.statustype', verbose_name='نوع لاگ')),
                ('acct_terminate_cause', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='radiuslog.terminatecause', verbose_name='علت خاتمه دادن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
