# Generated by Django 4.1.3 on 2022-12-03 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiuslog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlog',
            options={'ordering': ['-id']},
        ),
    ]
