# Generated by Django 4.1.3 on 2022-12-09 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiuslog', '0002_alter_userlog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounting',
            options={'ordering': ['-id'], 'verbose_name': 'مصرف کاربران'},
        ),
        migrations.AlterModelOptions(
            name='authenticate',
            options={'verbose_name': 'احراز هویت'},
        ),
        migrations.AlterModelOptions(
            name='userlog',
            options={'ordering': ['-id'], 'verbose_name': 'لاگ کاربران'},
        ),
    ]
