# Generated by Django 4.1.3 on 2022-12-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiuslog', '0003_alter_accounting_options_alter_authenticate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounting',
            options={'ordering': ['-id'], 'verbose_name': 'مصرف کاربر', 'verbose_name_plural': 'مصرف کاربران'},
        ),
        migrations.AlterModelOptions(
            name='authenticate',
            options={'verbose_name': 'احراز هویت', 'verbose_name_plural': 'احراز هویت ها'},
        ),
        migrations.AlterModelOptions(
            name='userlog',
            options={'ordering': ['-id'], 'verbose_name': 'لاگ کاربر', 'verbose_name_plural': 'لاگ کاربران'},
        ),
    ]
