# Generated by Django 4.1.3 on 2022-12-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiuslog', '0004_alter_accounting_options_alter_authenticate_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accounting',
            index=models.Index(fields=['user'], name='radiuslog_a_user_id_b2177b_idx'),
        ),
        migrations.AddIndex(
            model_name='accounting',
            index=models.Index(fields=['login_time'], name='radiuslog_a_login_t_c8c128_idx'),
        ),
        migrations.AddIndex(
            model_name='accounting',
            index=models.Index(fields=['user', 'login_time'], name='radiuslog_a_user_id_a59fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticate',
            index=models.Index(fields=['user'], name='radiuslog_a_user_id_2e0a09_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticate',
            index=models.Index(fields=['login_time'], name='radiuslog_a_login_t_216c3f_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticate',
            index=models.Index(fields=['user', 'login_time'], name='radiuslog_a_user_id_ab184a_idx'),
        ),
        migrations.AddIndex(
            model_name='userlog',
            index=models.Index(fields=['user'], name='radiuslog_u_user_id_4126ac_idx'),
        ),
        migrations.AddIndex(
            model_name='userlog',
            index=models.Index(fields=['log_time'], name='radiuslog_u_log_tim_a0a990_idx'),
        ),
        migrations.AddIndex(
            model_name='userlog',
            index=models.Index(fields=['dns_log'], name='radiuslog_u_dns_log_1aaea3_idx'),
        ),
        migrations.AddIndex(
            model_name='userlog',
            index=models.Index(fields=['user', 'log_time'], name='radiuslog_u_user_id_4f8e89_idx'),
        ),
        migrations.AddIndex(
            model_name='userlog',
            index=models.Index(fields=['user', 'dns_log'], name='radiuslog_u_user_id_c87c0b_idx'),
        ),
        migrations.AddIndex(
            model_name='userlog',
            index=models.Index(fields=['user', 'log_time', 'dns_log'], name='radiuslog_u_user_id_039f10_idx'),
        ),
    ]
